import { Label } from '@chadcn/upstream-shadcn/label';
import { useState } from 'react';
import { ArrowRight, Check, Layers, Palette, Search } from 'lucide-react';
import { Button } from '@chadcn/upstream-shadcn/button';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@chadcn/upstream-shadcn/card';
import { Input } from '@chadcn/upstream-shadcn/input';
import { Textarea } from '@chadcn/upstream-shadcn/textarea';
import { Checkbox } from '@chadcn/upstream-shadcn/checkbox';
import { Switch } from '@chadcn/upstream-shadcn/switch';
import { Progress } from '@chadcn/upstream-shadcn/progress';
import { Badge } from '@chadcn/upstream-shadcn/badge';
import Appearance from './Appearance';
import './home.css';

type Destination='components'|'blocks'|'apps'|'documentation';
export default function HomePage({navigate}:{navigate:(section:Destination)=>void}) {
 const [pressed,setPressed]=useState(false);
 const [notifications,setNotifications]=useState([true,true,false]);
 const [saved,setSaved]=useState(false);
 const [project,setProject]=useState('');
 const [created,setCreated]=useState('');
 const [period,setPeriod]=useState('Week');
 const [search,setSearch]=useState('');
 const [progress,setProgress]=useState(64);
 return <div className="home-page"><header className="home-header"><a className="wordmark" href="/">chadcn<span className="brand-square"/></a><nav aria-label="Browse">{(['components','blocks','apps','documentation'] as const).map(section=><Button variant="ghost" key={section} onClick={()=>navigate(section)}>{section[0].toUpperCase()+section.slice(1)}</Button>)}</nav><Appearance/></header>
 <main className="home-main"><section className="home-hero"><p className="eyebrow">ONE HOME FOR YOUR NEXT INTERFACE</p><h1>Good things,<br/><em>built together.</em></h1><p className="home-intro">Components, blocks, and starting points from across the ecosystem.<br className="home-break"/> Find your version. Make it yours. Build something good.</p><div className="home-actions"><Button size="lg" onClick={()=>navigate('components')}>Explore components <ArrowRight size={17}/></Button><Button size="lg" variant="outline" onClick={()=>navigate('documentation')}>Get started</Button></div><p className="home-caption">Real components below. Try them. Change the theme. See what fits.</p></section>
 <section className="home-showcase" aria-label="Interactive component showcase">
 <div className="home-column"><Card><CardHeader><CardTitle>Your building blocks</CardTitle><CardDescription>A few good defaults. Endless possibilities.</CardDescription></CardHeader><CardContent className="home-stack"><div className="home-row"><Button onClick={()=>setPressed(!pressed)}>{pressed?<><Check size={16}/>Selected</>:<>Button <ArrowRight size={16}/></>}</Button><Button variant="secondary" onClick={()=>navigate('blocks')}>Secondary</Button><Button variant="outline" onClick={()=>navigate('components')}>Outline</Button></div><Label className="home-field">Name<Input placeholder="Something worth building"/></Label><Label className="home-field">Message<Textarea placeholder="Start with an idea…"/></Label><div className="home-row home-spread"><div className="home-row"><Badge>New</Badge><Badge variant="secondary">Open source</Badge></div><Checkbox aria-label="Select example"/><Switch aria-label="Enable example"/></div></CardContent></Card>
 <Card><CardHeader><CardTitle>Find your people</CardTitle><CardDescription>A small team with big ideas.</CardDescription></CardHeader><CardContent className="home-stack"><div className="home-search"><Search size={16}/><Input aria-label="Find a teammate" placeholder="Find a teammate…" value={search} onChange={e=>setSearch(e.target.value)}/></div>{[['AL','Alex Lee','Design'],['JM','Jamie Morgan','Engineering'],['SR','Sam Rivera','Product']].filter(row=>row.join(' ').toLowerCase().includes(search.toLowerCase())).map(([initials,name,role])=><div className="home-person" key={name}><span className="home-avatar">{initials}</span><div><strong>{name}</strong><p>{role}</p></div><Badge variant="outline">Member</Badge></div>)}{search&&!['alex lee design','jamie morgan engineering','sam rivera product'].some(s=>s.includes(search.toLowerCase()))&&<p>No teammates found.</p>}</CardContent></Card></div>
 <div className="home-column"><Card><CardHeader><div className="home-row home-spread"><CardTitle>A little progress, every day.</CardTitle><Badge variant="secondary">+18%</Badge></div><CardDescription>Your team's activity at a glance.</CardDescription></CardHeader><CardContent className="home-stack"><div className="home-row" role="group" aria-label="Activity period">{['Week','Month'].map(p=><Button key={p} size="sm" variant={period===p?'default':'ghost'} aria-pressed={period===p} onClick={()=>setPeriod(p)}>{p}</Button>)}</div><div className="home-chart" role="img" aria-label={`${period} activity chart`}>{(period==='Week'?[35,65,49,88,72,97,60]:[44,57,70,62,87,96,81]).map((height,index)=><div key={index}><span style={{height:height*1.8}}/><small>{period==='Week'?['M','T','W','T','F','S','S'][index]:['Jan','Feb','Mar','Apr','May','Jun','Jul'][index]}</small></div>)}</div><div className="home-metrics"><div><span>Completed</span><strong>{period==='Week'?'32':'148'}</strong></div><div><span>In progress</span><strong>{period==='Week'?'8':'24'}</strong></div></div><Button variant="outline" onClick={()=>navigate('blocks')}>Explore dashboard blocks <ArrowRight size={16}/></Button></CardContent></Card>
 <Card><CardHeader><CardTitle>Make it feel like you.</CardTitle><CardDescription>One component. A different point of view.</CardDescription></CardHeader><CardContent className="home-stack"><div className="home-skin-icons"><Palette/><Layers/></div><p>Use the theme switcher above to change the colors, type, and shape of this entire page.</p><Button variant="secondary" onClick={()=>navigate('components')}>Find your version <ArrowRight size={16}/></Button></CardContent></Card></div>
 <div className="home-column"><Card><CardHeader><CardTitle>Start something new</CardTitle><CardDescription>Give your next project a place to grow.</CardDescription></CardHeader><CardContent><form className="home-stack" onSubmit={event=>{event.preventDefault();setCreated(project)}}><Label className="home-field">Project name<Input value={project} required onChange={e=>{setProject(e.target.value);setCreated('')}} placeholder="e.g. Our next great idea"/></Label><Label className="home-field">A few words about it<Textarea placeholder="What are you making?"/></Label><div className="home-row"><Checkbox id="home-private" defaultChecked/><Label htmlFor="home-private">Keep this project private</Label></div><Button type="submit">Create project <ArrowRight size={16}/></Button>{created&&<p role="status">“{created}” is ready in this preview.</p>}</form></CardContent></Card>
 <Card><CardHeader><CardTitle>Stay in the loop</CardTitle><CardDescription>Just the updates you want.</CardDescription></CardHeader><CardContent className="home-stack">{[['Product updates','New features and improvements.'],['Team activity','The things your people are building.'],['Weekly inspiration','A few things worth a look.']].map(([title,description],index)=><div key={title} className="home-notification"><div><Label htmlFor={`notice-${index}`}>{title}</Label><p>{description}</p></div><Switch id={`notice-${index}`} checked={notifications[index]} onCheckedChange={checked=>{setNotifications(values=>values.map((value,i)=>i===index?checked:value));setSaved(false)}}/></div>)}<Button variant="outline" onClick={()=>setSaved(true)}>{saved?<><Check size={16}/>Preferences saved</>:'Save preferences'}</Button></CardContent></Card>
 <Card><CardHeader><CardTitle>One step closer.</CardTitle><CardDescription>{progress}% of your weekly goal.</CardDescription></CardHeader><CardContent className="home-stack"><Progress value={progress} aria-label="Weekly goal"/><Button variant="ghost" onClick={()=>setProgress(value=>value>=100?0:Math.min(100,value+12))}>{progress>=100?'Start again':'Log a little progress'} <ArrowRight size={16}/></Button></CardContent></Card></div>
 </section><section className="home-closing"><h2>Your sources. Your style. Your next thing.</h2><p>Browse implementations from shadcn, Base UI, Radix, React Aria, Kibo, and more. Keep the versions that work for you, then compose them into something of your own.</p><Button size="lg" onClick={()=>navigate('components')}>Find your starting point <ArrowRight size={17}/></Button></section></main><footer className="home-footer"><span>chadcn — The interface library</span><Button variant="ghost" onClick={()=>navigate('documentation')}>Documentation <ArrowRight size={14}/></Button></footer></div>;
}
