import FirstPartyLibrary from './FirstPartyLibrary';
import { useEffect, useState } from 'react';
import profiles from '../data/library-profiles.json';
import { demos } from './demos/manifest';
import { Button } from '@chadcn/upstream-shadcn/button';
import { ArrowLeft, ArrowUpRight, GitCommitHorizontal, Star, GitFork } from 'lucide-react';
import './libraries.css';
const date=(value:string|null)=>value?new Date(value).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}):'Not verified';
export default function LibraryPages({id,source,query,onOpen,onBrowse}:{id:string|null;source:string;query:string;onOpen:(id:string|null)=>void;onBrowse:(id:string)=>void}){
 const [imageFailed,setImageFailed]=useState<string|null>(null);
 const snapshot=profiles.find(p=>p.id===id);
 const [updates,setUpdates]=useState<Record<string,{stars:number;forks:number;issues:number;fetchedAt:string;commits:{sha:string;title:string;date:string;url:string}[]}>>({});
 const [refreshError,setRefreshError]=useState<string|null>(null);
 useEffect(()=>{
  if(!snapshot||updates[snapshot.repository])return;
  const controller=new AbortController();const repository=snapshot.repository;
  const api='https://api.github.com/repos/'+repository.replace('https://github.com/','');
  Promise.all([fetch(api,{signal:controller.signal}),fetch(api+'/commits?per_page=6',{signal:controller.signal})]).then(async responses=>{
   if(responses.some(r=>!r.ok))throw Error('GitHub refresh unavailable');
   const [metadata,commits]=await Promise.all(responses.map(r=>r.json()));
   if(!Array.isArray(commits)||typeof metadata.stargazers_count!=='number')throw Error('Unexpected GitHub response');
   setUpdates(current=>({...current,[repository]:{stars:metadata.stargazers_count,forks:metadata.forks_count,issues:metadata.open_issues_count,fetchedAt:new Date().toISOString(),commits:commits.map(c=>({sha:c.sha,title:c.commit.message.split('\n')[0],date:c.commit.committer.date,url:c.html_url}))}}));setRefreshError(null);
  }).catch(()=>{if(!controller.signal.aborted)setRefreshError(repository)});
  return()=>controller.abort();
 },[snapshot?.repository]);
 const library=snapshot?{...snapshot,...updates[snapshot.repository]}:undefined;
 if(id==='chadcn'||source==='chadcn')return <FirstPartyLibrary onBrowse={()=>onBrowse('chadcn')}/>;
 if(!library)return <div className="library-index">{source==='all'&&(!query||'chadcn our registry'.includes(query.toLowerCase()))&&<Button variant="ghost" className="library-tile" onClick={()=>onOpen('chadcn')}><div><strong>chadcn</strong><p>Our own interface compositions and reusable components from across our projects.</p><span>Available examples and source-verified registry candidates</span></div></Button>}{profiles.filter(p=>(source==='all'||p.id===source)&&`${p.name} ${p.description} ${p.topics.join(' ')}`.toLowerCase().includes(query.toLowerCase())).map(p=><Button variant="ghost" className="library-tile" key={p.id} onClick={()=>onOpen(p.id)}><img loading="lazy" src={p.screenshot} alt={`${p.name} homepage screenshot`}/><div><strong>{p.name}</strong><p>{p.description}</p><span>{p.owner} · {p.license??'License unverified'} · {p.stars?.toLocaleString()??'—'} stars</span></div></Button>)}</div>;
 const previews=demos.filter(d=>d.source===library.id);
 return <article className="library-profile"><Button variant="ghost" onClick={()=>onOpen(null)}><ArrowLeft size={16}/>All libraries</Button><div className="library-title"><div><p className="eyebrow">{library.variant?'REGISTRY VARIANT':'LIBRARY PROFILE'}</p><h1>{library.name}</h1><p>{library.description}</p></div><div className="library-owner">{library.ownerAvatar&&<img src={library.ownerAvatar} alt=""/>}<div><small>Maintained by</small><a href={`https://github.com/${library.owner}`} target="_blank" rel="noreferrer">{library.owner}</a></div></div></div>
 <div className="library-actions">{previews.length>0&&<Button onClick={()=>onBrowse(library.id)}>Browse {previews.length} examples</Button>}<Button variant="outline" asChild><a href={library.homepage} target="_blank" rel="noreferrer">Homepage <ArrowUpRight size={15}/></a></Button><Button variant="outline" asChild><a href={library.repository} target="_blank" rel="noreferrer">GitHub repository <ArrowUpRight size={15}/></a></Button><Button variant="outline" asChild><a href={library.documentation} target="_blank" rel="noreferrer">Upstream documentation <ArrowUpRight size={15}/></a></Button></div>
 <figure className="library-screenshot">{imageFailed===library.id?<p>Homepage screenshot could not load.</p>:<img src={library.screenshot} alt={`${library.name} homepage, captured ${date(library.screenshotAt)}`} onError={()=>setImageFailed(library.id)}/>}<figcaption>Homepage snapshot · {date(library.screenshotAt)}{library.variant?' · Shared shadcn homepage':''}</figcaption></figure>
 <div className="library-facts"><div><span><Star size={16}/>Stars</span><strong>{library.stars?.toLocaleString()??'Not verified'}</strong></div><div><span><GitFork size={16}/>Forks</span><strong>{library.forks?.toLocaleString()??'Not verified'}</strong></div><div><span>Repository created</span><strong>{date(library.createdAt)}</strong></div><div><span>License</span><strong>{library.license??'Not verified'}</strong></div></div>
 <div className="library-details"><section><h2>About this library</h2>{library.variant&&<p>The {library.variant} implementation is part of the shadcn/ui repository. Its repository dates and activity below describe the shared project, not the launch date of this individual variant.</p>}<dl><dt>Creator / package author</dt><dd>{library.creator??'Not declared in the package metadata'}</dd><dt>First recorded commit author</dt><dd>{library.firstCommit?.author??'Not verified'}</dd><dt>First recorded commit</dt><dd>{library.firstCommit?<a href={`${library.repository}/commit/${library.firstCommit.sha}`} target="_blank" rel="noreferrer">{date(library.firstCommit.date)}</a>:'Not verified'}</dd><dt>Primary language</dt><dd>{library.language??'Not verified'}</dd><dt>Default branch</dt><dd>{library.defaultBranch??'Not verified'}</dd><dt>Open issues and pull requests</dt><dd>{library.issues?.toLocaleString()??'Not verified'}</dd><dt>Repository status</dt><dd>{library.archived?'Archived':'Active repository'}</dd><dt>In this collection</dt><dd>{library.itemCount} records · {library.packagedCount} packaged · {previews.length} previews</dd></dl><div className="library-topics">{library.topics.map(topic=><span key={topic}>{topic}</span>)}</div>{library.localCommit&&<p className="library-note">Local checkout: <a href={`${library.repository}/commit/${library.localCommit}`} target="_blank" rel="noreferrer">{library.localCommit.slice(0,8)}</a>. The recent activity alongside this reflects GitHub, which may be ahead of the local checkout.</p>}</section><section><h2>Recent commit history</h2><p className="library-note">{updates[library.repository]?'Refreshed from GitHub':'Saved GitHub snapshot'} · {date(library.fetchedAt)}.{refreshError===library.repository?' Refresh unavailable; showing the saved snapshot.':''}</p><ol className="library-commits">{library.commits.map(commit=><li key={commit.sha}><GitCommitHorizontal size={18}/><div><a href={commit.url} target="_blank" rel="noreferrer">{commit.title}</a><span>{date(commit.date)} · {commit.sha.slice(0,8)}</span></div></li>)}</ol><a href={`${library.repository}/commits`} target="_blank" rel="noreferrer">View full history on GitHub</a></section></div>
 <footer className="library-note">Facts sourced from <a href={`https://api.github.com/repos/${library.repository.replace('https://github.com/','')}`} target="_blank" rel="noreferrer">GitHub repository metadata</a>, commit history, and the upstream package manifest. Dates describe repository history and may differ from a library's public launch.</footer></article>;
}
