import type { Demo } from './manifest';
export const aiMoreEntries: Demo[] = [
{"id": "ai-elements:artifact", "title": "artifact", "source": "ai-elements", "kind": "Block", "description": "Interactive local example using the original AI Elements implementation.", "importPath": "@chadcn/upstream-ai-elements/artifact",load:()=>import('./AiMoreExamples').then(m=>({default:m.AiArtifactDemo}))},
{"id": "ai-elements:checkpoint", "title": "checkpoint", "source": "ai-elements", "kind": "Component", "description": "Interactive local example using the original AI Elements implementation.", "importPath": "@chadcn/upstream-ai-elements/checkpoint",load:()=>import('./AiMoreExamples').then(m=>({default:m.AiCheckpointDemo}))},
{"id": "ai-elements:confirmation", "title": "confirmation", "source": "ai-elements", "kind": "Component", "description": "Interactive local example using the original AI Elements implementation.", "importPath": "@chadcn/upstream-ai-elements/confirmation",load:()=>import('./AiMoreExamples').then(m=>({default:m.AiConfirmationDemo}))},
{"id": "ai-elements:context", "title": "context", "source": "ai-elements", "kind": "Component", "description": "Interactive local example using the original AI Elements implementation.", "importPath": "@chadcn/upstream-ai-elements/context",load:()=>import('./AiMoreExamples').then(m=>({default:m.AiContextDemo}))},
{"id": "ai-elements:conversation", "title": "conversation", "source": "ai-elements", "kind": "Block", "description": "Interactive local example using the original AI Elements implementation.", "importPath": "@chadcn/upstream-ai-elements/conversation",load:()=>import('./AiMoreExamples').then(m=>({default:m.AiConversationDemo}))},
{"id": "ai-elements:inline-citation", "title": "inline citation", "source": "ai-elements", "kind": "Component", "description": "Interactive local example using the original AI Elements implementation.", "importPath": "@chadcn/upstream-ai-elements/inline-citation",load:()=>import('./AiMoreExamples').then(m=>({default:m.AiCitationDemo}))},
{"id": "ai-elements:model-selector", "title": "model selector", "source": "ai-elements", "kind": "Component", "description": "Interactive local example using the original AI Elements implementation.", "importPath": "@chadcn/upstream-ai-elements/model-selector",load:()=>import('./AiMoreExamples').then(m=>({default:m.AiModelSelectorDemo}))},
{"id": "ai-elements:queue", "title": "queue", "source": "ai-elements", "kind": "Block", "description": "Interactive local example using the original AI Elements implementation.", "importPath": "@chadcn/upstream-ai-elements/queue",load:()=>import('./AiMoreExamples').then(m=>({default:m.AiQueueDemo}))},
{"id": "ai-elements:tool", "title": "tool", "source": "ai-elements", "kind": "Block", "description": "Interactive local example using the original AI Elements implementation.", "importPath": "@chadcn/upstream-ai-elements/tool",load:()=>import('./AiMoreExamples').then(m=>({default:m.AiToolDemo}))},
{"id": "ai-elements:transcription", "title": "transcription", "source": "ai-elements", "kind": "Component", "description": "Interactive local example using the original AI Elements implementation.", "importPath": "@chadcn/upstream-ai-elements/transcription",load:()=>import('./AiMoreExamples').then(m=>({default:m.AiTranscriptionDemo}))},
{"id": "ai-elements:web-preview", "title": "web preview", "source": "ai-elements", "kind": "Block", "description": "Interactive local example using the original AI Elements implementation.", "importPath": "@chadcn/upstream-ai-elements/web-preview",load:()=>import('./AiMoreExamples').then(m=>({default:m.AiWebPreviewDemo}))},
];
