import { useState } from 'react';
import { Button } from '@chadcn/upstream-shadcn/button';
import { Artifact, ArtifactContent, ArtifactDescription, ArtifactHeader, ArtifactTitle } from '@chadcn/upstream-ai-elements/artifact';
import { Checkpoint, CheckpointIcon, CheckpointTrigger } from '@chadcn/upstream-ai-elements/checkpoint';
import { CodeBlock } from '@chadcn/upstream-ai-elements/code-block';
import { Confirmation, ConfirmationActions, ConfirmationAccepted, ConfirmationAction, ConfirmationRequest, ConfirmationTitle } from '@chadcn/upstream-ai-elements/confirmation';
import { Context, ContextContent, ContextContentBody, ContextContentHeader, ContextInputUsage, ContextOutputUsage, ContextTrigger } from '@chadcn/upstream-ai-elements/context';
import { Conversation, ConversationContent, ConversationEmptyState } from '@chadcn/upstream-ai-elements/conversation';
import { InlineCitation, InlineCitationCard, InlineCitationCardBody, InlineCitationCardTrigger, InlineCitationQuote, InlineCitationSource, InlineCitationText } from '@chadcn/upstream-ai-elements/inline-citation';
import { ModelSelector, ModelSelectorContent, ModelSelectorGroup, ModelSelectorItem, ModelSelectorList, ModelSelectorName, ModelSelectorTrigger } from '@chadcn/upstream-ai-elements/model-selector';
import { Queue, QueueItem, QueueItemContent, QueueItemDescription, QueueItemIndicator, QueueList, QueueSection, QueueSectionContent, QueueSectionLabel, QueueSectionTrigger } from '@chadcn/upstream-ai-elements/queue';
import { Tool, ToolContent, ToolHeader, ToolInput, ToolOutput } from '@chadcn/upstream-ai-elements/tool';
import { Transcription, TranscriptionSegment } from '@chadcn/upstream-ai-elements/transcription';
import { WebPreview, WebPreviewBody, WebPreviewNavigation, WebPreviewUrl } from '@chadcn/upstream-ai-elements/web-preview';

export function AiArtifactDemo() { return <Artifact><ArtifactHeader><div><ArtifactTitle>Review notes</ArtifactTitle><ArtifactDescription>Local generated artifact</ArtifactDescription></div></ArtifactHeader><ArtifactContent><CodeBlock code={'const status = "ready";'} language="typescript" /></ArtifactContent></Artifact>; }
export function AiCheckpointDemo() { const [restored,setRestored]=useState(false); return <Checkpoint><CheckpointIcon /><CheckpointTrigger onClick={()=>setRestored(!restored)}>{restored?'Checkpoint restored · Reset':'Restore previous checkpoint'}</CheckpointTrigger></Checkpoint>; }
export function AiConfirmationDemo() { const [approved, setApproved] = useState(false); return <Confirmation approval={approved ? { id: 'local', approved: true } : undefined} state={approved ? 'approval-responded' : 'approval-requested'}><ConfirmationTitle>Run local formatter?</ConfirmationTitle>{approved?<ConfirmationAccepted>Approved locally.</ConfirmationAccepted>:<ConfirmationRequest>Changes stay in this preview.</ConfirmationRequest>}<ConfirmationActions><ConfirmationAction onClick={()=>setApproved(true)}>Approve</ConfirmationAction></ConfirmationActions></Confirmation>; }
export function AiContextDemo() { return <Context usedTokens={1240} maxTokens={4096} modelId="local-preview"><ContextTrigger/><ContextContent><ContextContentHeader>Token usage</ContextContentHeader><ContextContentBody><ContextInputUsage /><ContextOutputUsage /></ContextContentBody></ContextContent></Context>; }
export function AiConversationDemo() { return <Conversation className="min-h-40"><ConversationContent><ConversationEmptyState title="No messages yet" description="This local conversation is ready for input." /></ConversationContent></Conversation>; }
export function AiCitationDemo() { return <InlineCitation><InlineCitationText>Local source-backed answer</InlineCitationText><InlineCitationCard><InlineCitationCardTrigger sources={['https://example.com']} /><InlineCitationCardBody><InlineCitationSource title="Example source" url="https://example.com" description="Reference preview" /><InlineCitationQuote>Evidence stays linked to the cited source.</InlineCitationQuote></InlineCitationCardBody></InlineCitationCard></InlineCitation>; }
export function AiModelSelectorDemo() { const [model, setModel] = useState('Astra'); return <ModelSelector><ModelSelectorTrigger>{model}</ModelSelectorTrigger><ModelSelectorContent title="Choose model"><ModelSelectorList><ModelSelectorGroup heading="Local models"><ModelSelectorItem value="Astra" onSelect={()=>setModel('Astra')}><ModelSelectorName>Astra</ModelSelectorName></ModelSelectorItem><ModelSelectorItem value="Terra" onSelect={()=>setModel('Terra')}><ModelSelectorName>Terra</ModelSelectorName></ModelSelectorItem></ModelSelectorGroup></ModelSelectorList></ModelSelectorContent></ModelSelector>; }
export function AiQueueDemo() { return <Queue><QueueSection defaultOpen><QueueSectionTrigger>Queued tasks</QueueSectionTrigger><QueueSectionContent><QueueSectionLabel label="Background work" count={2} /><QueueList><QueueItem><QueueItemIndicator completed /><QueueItemContent completed>Index components</QueueItemContent><QueueItemDescription completed>Finished locally</QueueItemDescription></QueueItem><QueueItem><QueueItemIndicator /><QueueItemContent>Check links</QueueItemContent></QueueItem></QueueList></QueueSectionContent></QueueSection></Queue>; }
export function AiToolDemo() { return <Tool defaultOpen><ToolHeader type="tool-weather" state="output-available" title="Local tool result" /><ToolContent><ToolInput input={{ city: 'London' }} /><ToolOutput output={{ temperature: 18, unit: 'C' }} errorText={undefined} /></ToolContent></Tool>; }
export function AiTranscriptionDemo() { const [time,setTime]=useState(1); const segments=[{text:'A local transcript segment.',startSecond:0,endSecond:2},{text:'Click a segment to seek.',startSecond:2,endSecond:4}]; return <Transcription segments={segments} currentTime={time} onSeek={setTime}>{(segment,index)=><TranscriptionSegment key={index} segment={segment} index={index}>{segment.text}</TranscriptionSegment>}</Transcription>; }
export function AiWebPreviewDemo() { const [url,setUrl]=useState('https://example.com'); return <WebPreview defaultUrl={url} onUrlChange={setUrl}><WebPreviewNavigation><WebPreviewUrl value={url} onChange={event=>setUrl(event.target.value)} /></WebPreviewNavigation><WebPreviewBody src={url} title="External preview" /></WebPreview>; }
