import { Button } from '@chadcn/upstream-shadcn/button';
import { Input } from '@chadcn/upstream-shadcn/input';
import { useState } from 'react';
import { CalendarDate, CalendarDatePicker, CalendarDatePagination, CalendarHeader, CalendarMonthPicker, CalendarProvider, CalendarYearPicker } from '@chadcn/upstream-kibo/calendar';
import { Comparison, ComparisonHandle, ComparisonItem } from '@chadcn/upstream-kibo/comparison';
import { Cursor, CursorBody, CursorMessage, CursorName, CursorPointer } from '@chadcn/upstream-kibo/cursor';
import { Deck, DeckCards, DeckEmpty, DeckItem } from '@chadcn/upstream-kibo/deck';
import { Glimpse, GlimpseContent, GlimpseDescription, GlimpseTitle, GlimpseTrigger } from '@chadcn/upstream-kibo/glimpse';
import { QRCode } from '@chadcn/upstream-kibo/qr-code';
import { Marquee, MarqueeContent, MarqueeItem } from '@chadcn/upstream-kibo/marquee';
import { Snippet, SnippetCopyButton, SnippetHeader, SnippetTabsContent, SnippetTabsList, SnippetTabsTrigger } from '@chadcn/upstream-kibo/snippet';
import { TreeExpander, TreeIcon, TreeLabel, TreeNode, TreeNodeContent, TreeNodeTrigger, TreeProvider, TreeView } from '@chadcn/upstream-kibo/tree';
import { ContributionGraph, ContributionGraphBlock, ContributionGraphCalendar, ContributionGraphFooter, ContributionGraphLegend, ContributionGraphTotalCount } from '@chadcn/upstream-kibo/contribution-graph';
import { CreditCard, CreditCardChip, CreditCardExpiry, CreditCardFlipper, CreditCardFront, CreditCardLogo, CreditCardName, CreditCardNumber, CreditCardServiceProvider } from '@chadcn/upstream-kibo/credit-card';
import { ImageZoom } from '@chadcn/upstream-kibo/image-zoom';
import { Reel, ReelContent, ReelControls, ReelImage, ReelItem, ReelNextButton, ReelPreviousButton } from '@chadcn/upstream-kibo/reel';

export function KiboCalendarDemo() { return <CalendarProvider><CalendarDate><CalendarHeader /><CalendarDatePicker><CalendarMonthPicker /><CalendarYearPicker start={2024} end={2027} /></CalendarDatePicker><CalendarDatePagination /></CalendarDate><div className="p-3 text-sm">Use the month and year controls to browse the schedule.</div></CalendarProvider>; }
export function KiboComparisonDemo() { return <Comparison mode="drag" className="relative h-32 overflow-hidden rounded-lg"><ComparisonItem position="left" className="flex items-center justify-center bg-secondary">Before</ComparisonItem><ComparisonItem position="right" className="flex items-center justify-center bg-primary text-primary-foreground">After</ComparisonItem><ComparisonHandle className="absolute inset-y-0 left-1/2 w-1 bg-foreground" /></Comparison>; }
export function KiboDeckDemo() { return <Deck className="h-40"><DeckCards><DeckItem>First card</DeckItem><DeckItem>Second card</DeckItem><DeckItem>Third card</DeckItem><DeckEmpty /></DeckCards></Deck>; }
export function KiboCursorDemo() { return <Cursor><CursorPointer /><CursorBody><CursorName>Alex</CursorName><CursorMessage>Reviewing the new card layout</CursorMessage></CursorBody></Cursor>; }
export function KiboGlimpseDemo() { return <Glimpse><GlimpseTrigger asChild><Button type="button">Hover for preview</Button></GlimpseTrigger><GlimpseContent><GlimpseTitle>Design system</GlimpseTitle><GlimpseDescription>Shared components and tokens for the workspace.</GlimpseDescription></GlimpseContent></Glimpse>; }
export function KiboMarqueeDemo() { return <Marquee><MarqueeContent pauseOnHover autoFill><MarqueeItem>Design tokens</MarqueeItem><MarqueeItem>Component APIs</MarqueeItem><MarqueeItem>Accessible defaults</MarqueeItem></MarqueeContent></Marquee>; }
export function KiboQRCodeDemo() { const [value, setValue] = useState('https://example.com/docs'); return <div className="demo-form"><QRCode data={value} /><Input aria-label="QR code data" value={value} onChange={event => setValue(event.target.value)} /></div>; }
export function KiboSnippetDemo() { const code = 'npx chadcn-ux add button'; return <Snippet defaultValue="npm"><SnippetHeader><SnippetTabsList><SnippetTabsTrigger value="npm">npm</SnippetTabsTrigger><SnippetTabsTrigger value="pnpm">pnpm</SnippetTabsTrigger></SnippetTabsList><SnippetCopyButton value={code} /></SnippetHeader><SnippetTabsContent value="npm">{code}</SnippetTabsContent><SnippetTabsContent value="pnpm">pnpm dlx chadcn-ux add button</SnippetTabsContent></Snippet>; }
export function KiboTreeDemo() { return <TreeProvider defaultExpandedIds={['workspace']} selectable><TreeView><TreeNode nodeId="workspace"><TreeNodeTrigger><TreeExpander hasChildren /><TreeIcon hasChildren /><TreeLabel>Workspace</TreeLabel></TreeNodeTrigger><TreeNodeContent hasChildren><TreeNode nodeId="design"><TreeNodeTrigger><TreeIcon /><TreeLabel>Design tokens</TreeLabel></TreeNodeTrigger></TreeNode><TreeNode nodeId="components"><TreeNodeTrigger><TreeIcon /><TreeLabel>Components</TreeLabel></TreeNodeTrigger></TreeNode></TreeNodeContent></TreeNode></TreeView></TreeProvider>; }
export function KiboContributionDemo() { const data = Array.from({ length: 28 }, (_, index) => ({ date: new Date(Date.now() - (27 - index) * 86400000).toISOString(), count: index % 5, level: index % 5 })); return <ContributionGraph data={data} totalCount={56}><ContributionGraphCalendar>{({ activity, dayIndex, weekIndex }) => <ContributionGraphBlock key={`${weekIndex}-${dayIndex}`} activity={activity} dayIndex={dayIndex} weekIndex={weekIndex} />}</ContributionGraphCalendar><ContributionGraphFooter><ContributionGraphTotalCount /> <ContributionGraphLegend /></ContributionGraphFooter></ContributionGraph>; }
export function KiboCreditCardDemo() { return <CreditCard><CreditCardFlipper><CreditCardFront><CreditCardLogo>ACME</CreditCardLogo><CreditCardChip /><CreditCardNumber>4242 4242 4242 4242</CreditCardNumber><CreditCardName>Alex Morgan</CreditCardName><CreditCardExpiry>12/28</CreditCardExpiry><CreditCardServiceProvider type="Visa" /></CreditCardFront></CreditCardFlipper></CreditCard>; }
export function KiboImageZoomDemo() { return <ImageZoom><img alt="Abstract gradient" src="https://images.unsplash.com/photo-1557682250-33bd709cbe85?w=600" /></ImageZoom>; }
export function KiboReelDemo() { const data = [{ id: 1, type: 'image' as const, src: 'https://images.unsplash.com/photo-1557682250-33bd709cbe85?w=600', duration: 4, alt: 'Gradient' }]; return <Reel data={data} autoPlay={false}><ReelContent>{item => <ReelItem><ReelImage src={item.src} alt={item.alt ?? ''} className="h-40 w-full object-cover" /></ReelItem>}</ReelContent><ReelControls><ReelPreviousButton /><ReelNextButton /></ReelControls></Reel>; }
