import type { Demo } from './manifest';
/** Small, self-contained previews backed by the packaged Magic UI examples. */
export const magicExamples: Demo[] = [
  {
    id: 'magicui:aurora-text-demo', title: 'Aurora text', source: 'magicui', kind: 'Component',
    description: 'Animated gradient text with an aurora effect.', family: 'aurora-text',
    importPath: '@chadcn/upstream-magicui/aurora-text-demo',
    load: () => import('@chadcn/upstream-magicui/aurora-text-demo'),
  },
  {
    id: 'magicui:morphing-text-demo', title: 'Morphing text', source: 'magicui', kind: 'Component',
    description: 'Text that smoothly transitions between a sequence of words.', family: 'morphing-text',
    importPath: '@chadcn/upstream-magicui/morphing-text-demo',
    load: () => import('@chadcn/upstream-magicui/morphing-text-demo'),
  },
  {
    id: 'magicui:meteors-demo', title: 'Meteors', source: 'magicui', kind: 'Component',
    description: 'A meteor shower background effect for a focused content panel.', family: 'meteors',
    importPath: '@chadcn/upstream-magicui/meteors-demo',
    load: () => import('@chadcn/upstream-magicui/meteors-demo'),
  },
  {
    id: 'magicui:dot-pattern-demo', title: 'Dot pattern', source: 'magicui', kind: 'Component',
    description: 'An SVG dot pattern with a soft radial mask.', family: 'dot-pattern',
    importPath: '@chadcn/upstream-magicui/dot-pattern-demo',
    load: () => import('@chadcn/upstream-magicui/dot-pattern-demo'),
  },
  {
    id: 'magicui:retro-grid-demo', title: 'Retro grid', source: 'magicui', kind: 'Component',
    description: 'A perspective grid background with a neon gradient headline.', family: 'retro-grid',
    importPath: '@chadcn/upstream-magicui/retro-grid-demo',
    load: () => import('@chadcn/upstream-magicui/retro-grid-demo'),
  },
  {
    id: 'magicui:shimmer-button-demo', title: 'Shimmer button', source: 'magicui', kind: 'Component',
    description: 'A button with a moving shimmer highlight.', family: 'shimmer-button',
    importPath: '@chadcn/upstream-magicui/shimmer-button-demo',
    load: () => import('@chadcn/upstream-magicui/shimmer-button-demo'),
  },
  {
    id: 'magicui:animated-gradient-text-demo', title: 'Animated gradient text', source: 'magicui', kind: 'Component',
    description: 'A moving gradient treatment for announcement text.', family: 'animated-gradient-text',
    importPath: '@chadcn/upstream-magicui/animated-gradient-text-demo',
    load: () => import('@chadcn/upstream-magicui/animated-gradient-text-demo'),
  },
  {
    id: 'magicui:pulsating-button-demo', title: 'Pulsating button', source: 'magicui', kind: 'Component',
    description: 'A button with a pulsing attention ring.', family: 'pulsating-button',
    importPath: '@chadcn/upstream-magicui/pulsating-button-demo',
    load: () => import('@chadcn/upstream-magicui/pulsating-button-demo'),
  },
  {
    id: 'magicui:interactive-hover-button-demo', title: 'Interactive hover button', source: 'magicui', kind: 'Component',
    description: 'A button whose hover treatment follows the pointer.', family: 'interactive-hover-button',
    importPath: '@chadcn/upstream-magicui/interactive-hover-button-demo',
    load: () => import('@chadcn/upstream-magicui/interactive-hover-button-demo'),
  },
  {
    id: 'magicui:animated-circular-progress-bar-demo', title: 'Circular progress bar', source: 'magicui', kind: 'Component',
    description: 'An animated circular indicator for progress values.', family: 'animated-circular-progress-bar',
    importPath: '@chadcn/upstream-magicui/animated-circular-progress-bar-demo',
    load: () => import('@chadcn/upstream-magicui/animated-circular-progress-bar-demo'),
  },
  {
    id: 'magicui:avatar-circles-demo', title: 'Avatar circles', source: 'magicui', kind: 'Component',
    description: 'A compact overlapping group of avatar circles.', family: 'avatar-circles',
    importPath: '@chadcn/upstream-magicui/avatar-circles-demo',
    load: () => import('@chadcn/upstream-magicui/avatar-circles-demo'),
  },
  {
    id: 'magicui:grid-pattern-demo', title: 'Grid pattern', source: 'magicui', kind: 'Component',
    description: 'A responsive SVG grid background pattern.', family: 'grid-pattern',
    importPath: '@chadcn/upstream-magicui/grid-pattern-demo',
    load: () => import('@chadcn/upstream-magicui/grid-pattern-demo'),
  },
  {
    id: 'magicui:marquee-demo', title: 'Marquee', source: 'magicui', kind: 'Component',
    description: 'A continuously scrolling content marquee.', family: 'marquee',
    importPath: '@chadcn/upstream-magicui/marquee-demo',
    load: () => import('@chadcn/upstream-magicui/marquee-demo'),
  },
];

magicExamples.push(
  ...[
  { id: 'magicui:magic-card-demo', title: 'magic card demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/magic-card-demo', load: () => import('@chadcn/upstream-magicui/magic-card-demo') },
  { id: 'magicui:android-demo', title: 'android demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/android-demo', load: () => import('@chadcn/upstream-magicui/android-demo') },
  { id: 'magicui:android-demo-2', title: 'android demo 2', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/android-demo-2', load: () => import('@chadcn/upstream-magicui/android-demo-2') },
  { id: 'magicui:android-demo-3', title: 'android demo 3', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/android-demo-3', load: () => import('@chadcn/upstream-magicui/android-demo-3') },
  { id: 'magicui:warp-background-demo', title: 'warp background demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/warp-background-demo', load: () => import('@chadcn/upstream-magicui/warp-background-demo') },
  { id: 'magicui:line-shadow-text-demo', title: 'line shadow text demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/line-shadow-text-demo', load: () => import('@chadcn/upstream-magicui/line-shadow-text-demo') },
  { id: 'magicui:scroll-progress-demo', title: 'scroll progress demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/scroll-progress-demo', load: () => import('@chadcn/upstream-magicui/scroll-progress-demo') },
  { id: 'magicui:lens-demo', title: 'lens demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/lens-demo', load: () => import('@chadcn/upstream-magicui/lens-demo') },
  { id: 'magicui:lens-demo-2', title: 'lens demo 2', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/lens-demo-2', load: () => import('@chadcn/upstream-magicui/lens-demo-2') },
  { id: 'magicui:lens-demo-3', title: 'lens demo 3', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/lens-demo-3', load: () => import('@chadcn/upstream-magicui/lens-demo-3') },
  { id: 'magicui:pointer-demo-1', title: 'pointer demo 1', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/pointer-demo-1', load: () => import('@chadcn/upstream-magicui/pointer-demo-1') },
  { id: 'magicui:smooth-cursor-demo', title: 'smooth cursor demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/smooth-cursor-demo', load: () => import('@chadcn/upstream-magicui/smooth-cursor-demo') },
  { id: 'magicui:progressive-blur-demo', title: 'progressive blur demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/progressive-blur-demo', load: () => import('@chadcn/upstream-magicui/progressive-blur-demo') },
  { id: 'magicui:neon-gradient-card-demo', title: 'neon gradient card demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/neon-gradient-card-demo', load: () => import('@chadcn/upstream-magicui/neon-gradient-card-demo') },
  { id: 'magicui:striped-pattern-demo', title: 'striped pattern demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/striped-pattern-demo', load: () => import('@chadcn/upstream-magicui/striped-pattern-demo') },
  { id: 'magicui:flickering-grid-demo', title: 'flickering grid demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/flickering-grid-demo', load: () => import('@chadcn/upstream-magicui/flickering-grid-demo') },
  { id: 'magicui:flickering-grid-rounded-demo', title: 'flickering grid rounded demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/flickering-grid-rounded-demo', load: () => import('@chadcn/upstream-magicui/flickering-grid-rounded-demo') },
  { id: 'magicui:hero-video-dialog-demo', title: 'hero video dialog demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/hero-video-dialog-demo', load: () => import('@chadcn/upstream-magicui/hero-video-dialog-demo') },
  { id: 'magicui:hero-video-dialog-demo-top-in-bottom-out', title: 'hero video dialog demo top in bottom out', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/hero-video-dialog-demo-top-in-bottom-out', load: () => import('@chadcn/upstream-magicui/hero-video-dialog-demo-top-in-bottom-out') },
  { id: 'magicui:marquee-demo-vertical', title: 'marquee demo vertical', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/marquee-demo-vertical', load: () => import('@chadcn/upstream-magicui/marquee-demo-vertical') },
  { id: 'magicui:number-ticker-demo', title: 'number ticker demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/number-ticker-demo', load: () => import('@chadcn/upstream-magicui/number-ticker-demo') },
  { id: 'magicui:number-ticker-demo-2', title: 'number ticker demo 2', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/number-ticker-demo-2', load: () => import('@chadcn/upstream-magicui/number-ticker-demo-2') },
  { id: 'magicui:number-ticker-decimal-demo', title: 'number ticker decimal demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/number-ticker-decimal-demo', load: () => import('@chadcn/upstream-magicui/number-ticker-decimal-demo') },
  { id: 'magicui:ripple-demo', title: 'ripple demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/ripple-demo', load: () => import('@chadcn/upstream-magicui/ripple-demo') },
  { id: 'magicui:animated-list-demo', title: 'animated list demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/animated-list-demo', load: () => import('@chadcn/upstream-magicui/animated-list-demo') },
  { id: 'magicui:particles-demo', title: 'particles demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/particles-demo', load: () => import('@chadcn/upstream-magicui/particles-demo') },
  { id: 'magicui:animated-grid-pattern-demo', title: 'animated grid pattern demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/animated-grid-pattern-demo', load: () => import('@chadcn/upstream-magicui/animated-grid-pattern-demo') },
  { id: 'magicui:interactive-grid-pattern-demo', title: 'interactive grid pattern demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/interactive-grid-pattern-demo', load: () => import('@chadcn/upstream-magicui/interactive-grid-pattern-demo') },
  { id: 'magicui:interactive-grid-pattern-demo-2', title: 'interactive grid pattern demo 2', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/interactive-grid-pattern-demo-2', load: () => import('@chadcn/upstream-magicui/interactive-grid-pattern-demo-2') },
  { id: 'magicui:border-beam-demo', title: 'border beam demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/border-beam-demo', load: () => import('@chadcn/upstream-magicui/border-beam-demo') },
  { id: 'magicui:border-beam-demo-2', title: 'border beam demo 2', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/border-beam-demo-2', load: () => import('@chadcn/upstream-magicui/border-beam-demo-2') },
  { id: 'magicui:border-beam-demo-3', title: 'border beam demo 3', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/border-beam-demo-3', load: () => import('@chadcn/upstream-magicui/border-beam-demo-3') },
  { id: 'magicui:border-beam-demo-4', title: 'border beam demo 4', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/border-beam-demo-4', load: () => import('@chadcn/upstream-magicui/border-beam-demo-4') },
  { id: 'magicui:animated-beam-demo', title: 'animated beam demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/animated-beam-demo', load: () => import('@chadcn/upstream-magicui/animated-beam-demo') },
  { id: 'magicui:text-reveal-demo', title: 'text reveal demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/text-reveal-demo', load: () => import('@chadcn/upstream-magicui/text-reveal-demo') },
  { id: 'magicui:animated-gradient-text-demo-2', title: 'animated gradient text demo 2', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/animated-gradient-text-demo-2', load: () => import('@chadcn/upstream-magicui/animated-gradient-text-demo-2') },
  { id: 'magicui:orbiting-circles-demo', title: 'orbiting circles demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/orbiting-circles-demo', load: () => import('@chadcn/upstream-magicui/orbiting-circles-demo') },
  { id: 'magicui:dock-demo-2', title: 'dock demo 2', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/dock-demo-2', load: () => import('@chadcn/upstream-magicui/dock-demo-2') },
  { id: 'magicui:dock-demo-3', title: 'dock demo 3', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/dock-demo-3', load: () => import('@chadcn/upstream-magicui/dock-demo-3') },
  { id: 'magicui:word-rotate-demo', title: 'word rotate demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/word-rotate-demo', load: () => import('@chadcn/upstream-magicui/word-rotate-demo') },
  { id: 'magicui:hyper-text-demo', title: 'hyper text demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/hyper-text-demo', load: () => import('@chadcn/upstream-magicui/hyper-text-demo') },
  { id: 'magicui:typing-animation-demo', title: 'typing animation demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/typing-animation-demo', load: () => import('@chadcn/upstream-magicui/typing-animation-demo') },
  { id: 'magicui:typing-animation-demo-2', title: 'typing animation demo 2', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/typing-animation-demo-2', load: () => import('@chadcn/upstream-magicui/typing-animation-demo-2') },
  { id: 'magicui:typing-animation-demo-3', title: 'typing animation demo 3', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/typing-animation-demo-3', load: () => import('@chadcn/upstream-magicui/typing-animation-demo-3') },
  { id: 'magicui:typing-animation-demo-4', title: 'typing animation demo 4', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/typing-animation-demo-4', load: () => import('@chadcn/upstream-magicui/typing-animation-demo-4') },
  { id: 'magicui:typing-animation-demo-5', title: 'typing animation demo 5', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/typing-animation-demo-5', load: () => import('@chadcn/upstream-magicui/typing-animation-demo-5') },
  { id: 'magicui:typing-animation-demo-6', title: 'typing animation demo 6', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/typing-animation-demo-6', load: () => import('@chadcn/upstream-magicui/typing-animation-demo-6') },
  { id: 'magicui:typing-animation-demo-7', title: 'typing animation demo 7', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/typing-animation-demo-7', load: () => import('@chadcn/upstream-magicui/typing-animation-demo-7') },
  { id: 'magicui:typing-animation-demo-8', title: 'typing animation demo 8', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/typing-animation-demo-8', load: () => import('@chadcn/upstream-magicui/typing-animation-demo-8') },
  { id: 'magicui:scroll-based-velocity-demo', title: 'scroll based velocity demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/scroll-based-velocity-demo', load: () => import('@chadcn/upstream-magicui/scroll-based-velocity-demo') },
  { id: 'magicui:scroll-based-velocity-images-demo', title: 'scroll based velocity images demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/scroll-based-velocity-images-demo', load: () => import('@chadcn/upstream-magicui/scroll-based-velocity-images-demo') },
  { id: 'magicui:sparkles-text-demo', title: 'sparkles text demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/sparkles-text-demo', load: () => import('@chadcn/upstream-magicui/sparkles-text-demo') },
  { id: 'magicui:spinning-text-demo', title: 'spinning text demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/spinning-text-demo', load: () => import('@chadcn/upstream-magicui/spinning-text-demo') },
  { id: 'magicui:spinning-text-demo-2', title: 'spinning text demo 2', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/spinning-text-demo-2', load: () => import('@chadcn/upstream-magicui/spinning-text-demo-2') },
  { id: 'magicui:comic-text-demo', title: 'comic text demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/comic-text-demo', load: () => import('@chadcn/upstream-magicui/comic-text-demo') },
  { id: 'magicui:icon-cloud-demo', title: 'icon cloud demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/icon-cloud-demo', load: () => import('@chadcn/upstream-magicui/icon-cloud-demo') },
  { id: 'magicui:icon-cloud-demo-2', title: 'icon cloud demo 2', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/icon-cloud-demo-2', load: () => import('@chadcn/upstream-magicui/icon-cloud-demo-2') },
  { id: 'magicui:icon-cloud-demo-3', title: 'icon cloud demo 3', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/icon-cloud-demo-3', load: () => import('@chadcn/upstream-magicui/icon-cloud-demo-3') },
  { id: 'magicui:text-animate-demo', title: 'text animate demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/text-animate-demo', load: () => import('@chadcn/upstream-magicui/text-animate-demo') },
  { id: 'magicui:text-animate-demo-2', title: 'text animate demo 2', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/text-animate-demo-2', load: () => import('@chadcn/upstream-magicui/text-animate-demo-2') },
  { id: 'magicui:text-animate-demo-3', title: 'text animate demo 3', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/text-animate-demo-3', load: () => import('@chadcn/upstream-magicui/text-animate-demo-3') },
  { id: 'magicui:text-animate-demo-4', title: 'text animate demo 4', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/text-animate-demo-4', load: () => import('@chadcn/upstream-magicui/text-animate-demo-4') },
  { id: 'magicui:text-animate-demo-5', title: 'text animate demo 5', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/text-animate-demo-5', load: () => import('@chadcn/upstream-magicui/text-animate-demo-5') },
  { id: 'magicui:text-animate-demo-6', title: 'text animate demo 6', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/text-animate-demo-6', load: () => import('@chadcn/upstream-magicui/text-animate-demo-6') },
  { id: 'magicui:text-animate-demo-7', title: 'text animate demo 7', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/text-animate-demo-7', load: () => import('@chadcn/upstream-magicui/text-animate-demo-7') },
  { id: 'magicui:text-animate-demo-8', title: 'text animate demo 8', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/text-animate-demo-8', load: () => import('@chadcn/upstream-magicui/text-animate-demo-8') },
  { id: 'magicui:text-animate-demo-9', title: 'text animate demo 9', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/text-animate-demo-9', load: () => import('@chadcn/upstream-magicui/text-animate-demo-9') },
  { id: 'magicui:shiny-button-demo', title: 'shiny button demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/shiny-button-demo', load: () => import('@chadcn/upstream-magicui/shiny-button-demo') },
  { id: 'magicui:shine-border-demo', title: 'shine border demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/shine-border-demo', load: () => import('@chadcn/upstream-magicui/shine-border-demo') },
  { id: 'magicui:shine-border-demo-2', title: 'shine border demo 2', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/shine-border-demo-2', load: () => import('@chadcn/upstream-magicui/shine-border-demo-2') },
  { id: 'magicui:cool-mode-demo', title: 'cool mode demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/cool-mode-demo', load: () => import('@chadcn/upstream-magicui/cool-mode-demo') },
  { id: 'magicui:ripple-button-demo', title: 'ripple button demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/ripple-button-demo', load: () => import('@chadcn/upstream-magicui/ripple-button-demo') },
  { id: 'magicui:file-tree-demo', title: 'file tree demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/file-tree-demo', load: () => import('@chadcn/upstream-magicui/file-tree-demo') },
  { id: 'magicui:blur-fade-demo', title: 'blur fade demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/blur-fade-demo', load: () => import('@chadcn/upstream-magicui/blur-fade-demo') },
  { id: 'magicui:blur-fade-text-demo', title: 'blur fade text demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/blur-fade-text-demo', load: () => import('@chadcn/upstream-magicui/blur-fade-text-demo') },
  { id: 'magicui:safari-demo', title: 'safari demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/safari-demo', load: () => import('@chadcn/upstream-magicui/safari-demo') },
  { id: 'magicui:safari-demo-2', title: 'safari demo 2', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/safari-demo-2', load: () => import('@chadcn/upstream-magicui/safari-demo-2') },
  { id: 'magicui:safari-demo-3', title: 'safari demo 3', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/safari-demo-3', load: () => import('@chadcn/upstream-magicui/safari-demo-3') },
  { id: 'magicui:safari-demo-4', title: 'safari demo 4', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/safari-demo-4', load: () => import('@chadcn/upstream-magicui/safari-demo-4') },
  { id: 'magicui:iphone-demo', title: 'iphone demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/iphone-demo', load: () => import('@chadcn/upstream-magicui/iphone-demo') },
  { id: 'magicui:iphone-demo-2', title: 'iphone demo 2', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/iphone-demo-2', load: () => import('@chadcn/upstream-magicui/iphone-demo-2') },
  { id: 'magicui:iphone-demo-3', title: 'iphone demo 3', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/iphone-demo-3', load: () => import('@chadcn/upstream-magicui/iphone-demo-3') },
  { id: 'magicui:rainbow-button-demo', title: 'rainbow button demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/rainbow-button-demo', load: () => import('@chadcn/upstream-magicui/rainbow-button-demo') },
  { id: 'magicui:rainbow-button-demo-2', title: 'rainbow button demo 2', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/rainbow-button-demo-2', load: () => import('@chadcn/upstream-magicui/rainbow-button-demo-2') },
  { id: 'magicui:terminal-demo', title: 'terminal demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/terminal-demo', load: () => import('@chadcn/upstream-magicui/terminal-demo') },
  { id: 'magicui:terminal-demo-2', title: 'terminal demo 2', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/terminal-demo-2', load: () => import('@chadcn/upstream-magicui/terminal-demo-2') },
  { id: 'magicui:video-text-demo', title: 'video text demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/video-text-demo', load: () => import('@chadcn/upstream-magicui/video-text-demo') },
  { id: 'magicui:pixel-image-demo', title: 'pixel image demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/pixel-image-demo', load: () => import('@chadcn/upstream-magicui/pixel-image-demo') },
  { id: 'magicui:animated-theme-toggler-demo', title: 'animated theme toggler demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/animated-theme-toggler-demo', load: () => import('@chadcn/upstream-magicui/animated-theme-toggler-demo') },
  { id: 'magicui:light-rays-demo', title: 'light rays demo', source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/light-rays-demo', load: () => import('@chadcn/upstream-magicui/light-rays-demo') },
  ],
);

const additionalMagicLoads = {
  'striped-pattern-dashed': () => import('@chadcn/upstream-magicui/striped-pattern-dashed'),
  'striped-pattern-right': () => import('@chadcn/upstream-magicui/striped-pattern-right'),
  'grid-pattern-linear-gradient': () => import('@chadcn/upstream-magicui/grid-pattern-linear-gradient'),
  'grid-pattern-dashed': () => import('@chadcn/upstream-magicui/grid-pattern-dashed'),
  'dot-pattern-linear-gradient': () => import('@chadcn/upstream-magicui/dot-pattern-linear-gradient'),
  'dot-pattern-with-glow-effect': () => import('@chadcn/upstream-magicui/dot-pattern-with-glow-effect'),
  'code-comparison-demo': () => import('@chadcn/upstream-magicui/code-comparison-demo'),
  'marquee-logos': () => import('@chadcn/upstream-magicui/marquee-logos'),
  'marquee-3d': () => import('@chadcn/upstream-magicui/marquee-3d'),
  'globe-demo': () => import('@chadcn/upstream-magicui/globe-demo'),
  'tweet-card-demo': () => import('./MagicTweetExample').then(m => ({default:m.MagicTweetNetworkDemo})),
  'tweet-card-images': () => import('@chadcn/upstream-magicui/tweet-card-images'),
  'tweet-card-meta-preview': () => import('@chadcn/upstream-magicui/tweet-card-meta-preview'),
  'bento-demo': () => import('@chadcn/upstream-magicui/bento-demo'),
  'bento-demo-vertical': () => import('@chadcn/upstream-magicui/bento-demo-vertical'),
  'animated-shiny-text-demo': () => import('@chadcn/upstream-magicui/animated-shiny-text-demo'),
  'animated-beam-unidirectional': () => import('@chadcn/upstream-magicui/animated-beam-unidirectional'),
  'animated-beam-bidirectional': () => import('@chadcn/upstream-magicui/animated-beam-bidirectional'),
  'animated-beam-multiple-inputs': () => import('@chadcn/upstream-magicui/animated-beam-multiple-inputs'),
  'animated-beam-multiple-outputs': () => import('@chadcn/upstream-magicui/animated-beam-multiple-outputs'),
  'dock-demo': () => import('@chadcn/upstream-magicui/dock-demo'),
  'confetti-demo': () => import('@chadcn/upstream-magicui/confetti-demo'),
  'confetti-basic-cannon': () => import('@chadcn/upstream-magicui/confetti-basic-cannon'),
  'confetti-random-direction': () => import('@chadcn/upstream-magicui/confetti-random-direction'),
  'confetti-fireworks': () => import('@chadcn/upstream-magicui/confetti-fireworks'),
  'confetti-stars': () => import('@chadcn/upstream-magicui/confetti-stars'),
  'confetti-side-cannons': () => import('@chadcn/upstream-magicui/confetti-side-cannons'),
  'confetti-custom-shapes': () => import('@chadcn/upstream-magicui/confetti-custom-shapes'),
  'confetti-emoji': () => import('@chadcn/upstream-magicui/confetti-emoji'),
  'cool-mode-custom': () => import('@chadcn/upstream-magicui/cool-mode-custom'),
  'highlighter-demo': () => import('@chadcn/upstream-magicui/highlighter-demo'),
  'dotted-map-demo': () => import('@chadcn/upstream-magicui/dotted-map-demo'),
  'dotted-map-demo-2': () => import('@chadcn/upstream-magicui/dotted-map-demo-2'),
} as const;

for (const [slug, load] of Object.entries(additionalMagicLoads)) {
  magicExamples.push({ id: 'magicui:' + slug, family: ['bento-demo','bento-demo-vertical'].includes(slug) ? 'bento-grid' : undefined, title: slug.replaceAll('-', ' '), source: 'magicui', kind: 'Component', description: 'Original packaged Magic UI example running from the upstream registry.', importPath: '@chadcn/upstream-magicui/' + slug, load });
}

magicExamples.push({ id: 'magicui:client-tweet-card-fixture', defaultExample: true, family: 'tweet-card', title: 'Tweet card — local fixture', source: 'magicui', kind: 'Component', description: 'Actual ClientTweetCard rendered with explicitly illustrative local data. No external service is required.', importPath: '@chadcn/upstream-magicui/client-tweet-card', load: () => import('./MagicTweetExample').then(m => ({default:m.MagicTweetFixtureDemo})) });

for (const demo of magicExamples) {
  if (['magicui:icon-cloud-demo','magicui:marquee-logos'].includes(demo.id)) demo.description='Original Magic UI composition using bundled logo assets in place of unavailable CDN URLs.';
  if (demo.id==='magicui:tweet-card-demo') { demo.title='Tweet card — external service'; demo.description='Original upstream tweet ID rendered by ClientTweetCard. This variant requires the external tweet service; the local fixture is available alongside it.'; }
}
