import type { Demo } from './manifest';

export const providerShowcaseEntries: Demo[] = [
  { id: 'shadcn-base:preview', family: 'preview', variantLabel: 'Base UI', title: 'Preview', source: 'shadcn-base', kind: 'Block', description: 'Packaged Base UI preview block.', importPath: '@chadcn/upstream-shadcn-base/preview', load: () => import('@chadcn/upstream-shadcn-base/preview') },
  { id: 'shadcn-base:preview-02', family: 'preview-02', variantLabel: 'Base UI', title: 'Preview 02', source: 'shadcn-base', kind: 'Block', description: 'Packaged Base UI preview block.', importPath: '@chadcn/upstream-shadcn-base/preview-02', load: () => import('@chadcn/upstream-shadcn-base/preview-02') },
  { id: 'shadcn-base:preview-03', family: 'preview-03', variantLabel: 'Base UI', title: 'Preview 03', source: 'shadcn-base', kind: 'Block', description: 'Packaged Base UI preview block.', importPath: '@chadcn/upstream-shadcn-base/preview-03', load: () => import('@chadcn/upstream-shadcn-base/preview-03') },
  { id: 'shadcn-base:dashboard-01', family: 'dashboard-01', variantLabel: 'Base UI', title: 'Dashboard 01', source: 'shadcn-base', kind: 'Block', description: 'Packaged Base UI dashboard block.', importPath: '@chadcn/upstream-shadcn-base/dashboard-01', load: () => import('@chadcn/upstream-shadcn-base/dashboard-01') },
  { id: 'shadcn-radix:preview', family: 'preview', variantLabel: 'Radix UI', title: 'Preview', source: 'shadcn-radix', kind: 'Block', description: 'Packaged Radix UI preview block.', importPath: '@chadcn/upstream-shadcn-radix/preview', load: () => import('@chadcn/upstream-shadcn-radix/preview') },
  { id: 'shadcn-radix:preview-02', family: 'preview-02', variantLabel: 'Radix UI', title: 'Preview 02', source: 'shadcn-radix', kind: 'Block', description: 'Packaged Radix UI preview block.', importPath: '@chadcn/upstream-shadcn-radix/preview-02', load: () => import('@chadcn/upstream-shadcn-radix/preview-02') },
  { id: 'shadcn-radix:preview-03', family: 'preview-03', variantLabel: 'Radix UI', title: 'Preview 03', source: 'shadcn-radix', kind: 'Block', description: 'Packaged Radix UI preview block.', importPath: '@chadcn/upstream-shadcn-radix/preview-03', load: () => import('@chadcn/upstream-shadcn-radix/preview-03') },
  { id: 'shadcn-radix:dashboard-01', family: 'dashboard-01', variantLabel: 'Radix UI', title: 'Dashboard 01', source: 'shadcn-radix', kind: 'Block', description: 'Packaged Radix UI dashboard block.', importPath: '@chadcn/upstream-shadcn-radix/dashboard-01', load: () => import('@chadcn/upstream-shadcn-radix/dashboard-01') },
  { id: 'shadcn-aria:preview', family: 'preview', variantLabel: 'React Aria', title: 'Preview', source: 'shadcn-aria', kind: 'Block', description: 'Packaged React Aria preview block.', importPath: '@chadcn/upstream-shadcn-aria/preview', load: () => import('@chadcn/upstream-shadcn-aria/preview') },
  { id: 'shadcn-aria:preview-02', family: 'preview-02', variantLabel: 'React Aria', title: 'Preview 02', source: 'shadcn-aria', kind: 'Block', description: 'Packaged React Aria preview block.', importPath: '@chadcn/upstream-shadcn-aria/preview-02', load: () => import('@chadcn/upstream-shadcn-aria/preview-02') },
  { id: 'shadcn-aria:preview-03', family: 'preview-03', variantLabel: 'React Aria', title: 'Preview 03', source: 'shadcn-aria', kind: 'Block', description: 'Packaged React Aria preview block.', importPath: '@chadcn/upstream-shadcn-aria/preview-03', load: () => import('@chadcn/upstream-shadcn-aria/preview-03') },
  { id: 'shadcn-aria:dashboard-01', family: 'dashboard-01', variantLabel: 'React Aria', title: 'Dashboard 01', source: 'shadcn-aria', kind: 'Block', description: 'Packaged React Aria dashboard block.', importPath: '@chadcn/upstream-shadcn-aria/dashboard-01', load: () => import('@chadcn/upstream-shadcn-aria/dashboard-01') },
];
