import { useState } from 'react';
import { Calendar } from '@chadcn/upstream-shadcn-cssinjs/calendar';
import { ScrollArea } from '@chadcn/upstream-shadcn-cssinjs/scroll-area';
import { Menubar, MenubarMenu, MenubarTrigger, MenubarContent, MenubarItem, MenubarSeparator } from '@chadcn/upstream-shadcn-cssinjs/menubar';
import { NavigationMenu, NavigationMenuList, NavigationMenuItem, NavigationMenuTrigger, NavigationMenuContent, NavigationMenuLink } from '@chadcn/upstream-shadcn-cssinjs/navigation-menu';

export function CalendarDemo(){const [date,setDate]=useState<Date|undefined>(new Date(2026,8,6));return <div><Calendar mode="single" selected={date} onSelect={setDate}/><p aria-live="polite">{date?.toLocaleDateString()??'Choose a date'}</p></div>}
export function ScrollAreaDemo(){return <ScrollArea style={{height:240,width:280}}><div style={{padding:16}}>{Array.from({length:30},(_,i)=><p key={i}>Release {30-i} · Component improvements</p>)}</div></ScrollArea>}
export function MenubarDemo(){const [action,setAction]=useState('No action selected');return <div><Menubar><MenubarMenu><MenubarTrigger>File</MenubarTrigger><MenubarContent><MenubarItem onClick={()=>setAction('New document created')}>New document</MenubarItem><MenubarItem onClick={()=>setAction('Document saved')}>Save</MenubarItem><MenubarSeparator/><MenubarItem onClick={()=>setAction('Document closed')}>Close</MenubarItem></MenubarContent></MenubarMenu><MenubarMenu><MenubarTrigger>Edit</MenubarTrigger><MenubarContent><MenubarItem onClick={()=>setAction('Last change undone')}>Undo</MenubarItem><MenubarItem onClick={()=>setAction('Change restored')}>Redo</MenubarItem></MenubarContent></MenubarMenu></Menubar><p aria-live="polite">{action}</p></div>}
export function NavigationMenuDemo(){const [selected,setSelected]=useState('Choose a destination');return <div><NavigationMenu><NavigationMenuList><NavigationMenuItem><NavigationMenuTrigger>Library</NavigationMenuTrigger><NavigationMenuContent>{['Components','Blocks','Apps'].map(name=><NavigationMenuLink key={name} href={'#'+name.toLowerCase()} onClick={()=>setSelected(name)}>{name}</NavigationMenuLink>)}</NavigationMenuContent></NavigationMenuItem></NavigationMenuList></NavigationMenu><p aria-live="polite">{selected}</p></div>}
