import type { Demo } from './manifest';

export const stylexMoreEntries: Demo[] = [
  ...(['alert','badge','card','dialog','select','tabs','switch','slider','progress','avatar','separator','tooltip','popover'] as const).map(name => ({ id: `shadcn-cssinjs:${name}`, family: name, variantLabel: 'StyleX', title: name[0].toUpperCase() + name.slice(1), source: 'shadcn-cssinjs', kind: 'Component', description: `The ${name} primitive rendered by the StyleX adapter.`, importPath: `@chadcn/upstream-shadcn-cssinjs/${name}`, load: () => import('./StylexMoreExamples').then(m => ({ default: m[`Stylex${name[0].toUpperCase()}${name.slice(1)}Demo` as keyof typeof m] })) })),
  { id: 'shadcn-cssinjs:textarea', family: 'textarea', variantLabel: 'StyleX', title: 'Textarea', source: 'shadcn-cssinjs', kind: 'Component', description: 'Textarea rendered by the StyleX adapter.', importPath: '@chadcn/upstream-shadcn-cssinjs/textarea', load: () => import('./StylexMoreExamples').then(m => ({ default: m.StylexTextareaDemo })) },
  { id: 'shadcn-cssinjs:table', family: 'table', variantLabel: 'StyleX', title: 'Table', source: 'shadcn-cssinjs', kind: 'Component', description: 'Table rendered by the StyleX adapter.', importPath: '@chadcn/upstream-shadcn-cssinjs/table', load: () => import('./StylexMoreExamples').then(m => ({ default: m.StylexTableDemo })) },
  { id: 'shadcn-cssinjs:empty', family: 'empty', variantLabel: 'StyleX', title: 'Empty state', source: 'shadcn-cssinjs', kind: 'Component', description: 'Empty state rendered by the StyleX adapter.', importPath: '@chadcn/upstream-shadcn-cssinjs/empty', load: () => import('./StylexMoreExamples').then(m => ({ default: m.StylexEmptyDemo })) },
  { id: 'shadcn-cssinjs:field', family: 'field', variantLabel: 'StyleX', title: 'Field', source: 'shadcn-cssinjs', kind: 'Component', description: 'Form field rendered by the StyleX adapter.', importPath: '@chadcn/upstream-shadcn-cssinjs/field', load: () => import('./StylexMoreExamples').then(m => ({ default: m.StylexFieldDemo })) },
];
