import { Label } from '@chadcn/upstream-shadcn-cssinjs/label';
import { Input } from '@chadcn/upstream-shadcn-cssinjs/input';
import { Textarea } from '@chadcn/upstream-shadcn-cssinjs/textarea';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@chadcn/upstream-shadcn-cssinjs/table';
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyTitle } from '@chadcn/upstream-shadcn-cssinjs/empty';
import { Field, FieldDescription, FieldLabel, FieldSet } from '@chadcn/upstream-shadcn-cssinjs/field';
import { Button } from '@chadcn/upstream-shadcn-cssinjs/button';
import { Alert, AlertDescription, AlertTitle } from '@chadcn/upstream-shadcn-cssinjs/alert';
import { Badge } from '@chadcn/upstream-shadcn-cssinjs/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@chadcn/upstream-shadcn-cssinjs/card';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@chadcn/upstream-shadcn-cssinjs/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@chadcn/upstream-shadcn-cssinjs/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@chadcn/upstream-shadcn-cssinjs/tabs';
import { Switch } from '@chadcn/upstream-shadcn-cssinjs/switch';
import { Slider } from '@chadcn/upstream-shadcn-cssinjs/slider';
import { Progress } from '@chadcn/upstream-shadcn-cssinjs/progress';
import { Avatar, AvatarFallback } from '@chadcn/upstream-shadcn-cssinjs/avatar';
import { Separator } from '@chadcn/upstream-shadcn-cssinjs/separator';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@chadcn/upstream-shadcn-cssinjs/tooltip';
import { Popover, PopoverContent, PopoverTrigger } from '@chadcn/upstream-shadcn-cssinjs/popover';

export const StylexTextareaDemo = () => <div className="demo-form"><Label htmlFor="stylex-more-notes">Notes</Label><Textarea id="stylex-more-notes" defaultValue="A place for the things we are building together." rows={4} /><p>Textarea from the StyleX adapter.</p></div>;
export const StylexTableDemo = () => <Table><TableHeader><TableRow><TableHead>Project</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>Atlas</TableCell><TableCell>Active</TableCell></TableRow><TableRow><TableCell>Orbit</TableCell><TableCell>Planning</TableCell></TableRow></TableBody></Table>;
export const StylexEmptyDemo = () => <Empty><EmptyHeader><EmptyTitle>No projects yet</EmptyTitle><EmptyDescription>Create a project to start organizing your work.</EmptyDescription></EmptyHeader><EmptyContent><Button>Create project</Button></EmptyContent></Empty>;
export const StylexFieldDemo = () => <FieldSet><Field><FieldLabel htmlFor="stylex-project-name">Project name</FieldLabel><Input id="stylex-project-name" placeholder="Atlas" /><FieldDescription>A short name for your project.</FieldDescription></Field></FieldSet>;
export const StylexAlertDemo = () => <Alert><AlertTitle>Heads up</AlertTitle><AlertDescription>This is a StyleX alert.</AlertDescription></Alert>;
export const StylexBadgeDemo = () => <div className="demo-button-row"><Badge>Default</Badge><Badge variant="secondary">Secondary</Badge><Badge variant="outline">Outline</Badge></div>;
export const StylexCardDemo = () => <Card><CardHeader><CardTitle>Collection</CardTitle></CardHeader><CardContent>A StyleX card composition.</CardContent></Card>;
export const StylexDialogDemo = () => <Dialog><DialogTrigger>Open dialog</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Confirm action</DialogTitle><DialogDescription>A StyleX dialog composition.</DialogDescription></DialogHeader></DialogContent></Dialog>;
export const StylexSelectDemo = () => <Select defaultValue="one"><SelectTrigger><SelectValue placeholder="Choose one" /></SelectTrigger><SelectContent><SelectItem value="one">One</SelectItem><SelectItem value="two">Two</SelectItem></SelectContent></Select>;
export const StylexTabsDemo = () => <Tabs defaultValue="overview"><TabsList><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="details">Details</TabsTrigger></TabsList><TabsContent value="overview">Overview content</TabsContent><TabsContent value="details">Details content</TabsContent></Tabs>;
export const StylexSwitchDemo = () => <Switch defaultChecked aria-label="Enable notifications" />;
export const StylexSliderDemo = () => <Slider defaultValue={[40]} min={0} max={100} />;
export const StylexProgressDemo = () => <Progress value={64} />;
export const StylexAvatarDemo = () => <Avatar><AvatarFallback>CH</AvatarFallback></Avatar>;
export const StylexSeparatorDemo = () => <div><span>Above</span><Separator /><span>Below</span></div>;
export const StylexTooltipDemo = () => <TooltipProvider><Tooltip><TooltipTrigger>Hover for details</TooltipTrigger><TooltipContent>StyleX tooltip</TooltipContent></Tooltip></TooltipProvider>;
export const StylexPopoverDemo = () => <Popover><PopoverTrigger>Open popover</PopoverTrigger><PopoverContent>StyleX popover content.</PopoverContent></Popover>;
